# Generated by Django 3.0.1 on 2020-01-14 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('publish_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('vtype', models.PositiveSmallIntegerField(
                    choices=[(1, 'Дискретный выбор'), (2, 'Один из многих'), (3, 'Несколько из многих')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
