# Generated by Django 3.0.1 on 2020-01-28 10:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_leavelike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveLike',
            new_name='LikeModel',
        ),
    ]
