# Generated by Django 3.0.1 on 2020-01-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20200128_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vtype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sent to staff members'), (1, 'Consideration in progress'), (2, 'Approved'), (3, 'Declined')], default=1),
        ),
        migrations.AlterField(
            model_name='voting',
            name='vtype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Single'), (1, 'Multiple')], default=1),
        ),
    ]
