# Generated by Django 3.0.1 on 2020-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votevariant',
            name='vote',
        ),
        migrations.AddField(
            model_name='voting',
            name='votes',
            field=models.ManyToManyField(to='main.VoteVariant'),
        ),
    ]
